#############################################################################
# Makefile for building: Box2D
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  box2D.pro
# Template: app
# Command: /opt/qt/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile box2D.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/home/i7469762/Documents/box2D/include -IGLFunctionsLib/include -I/opt/qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Box2D1.0.0
DISTDIR = /home/i7469762/Documents/box2D/.tmp/Box2D1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qt/5.5/gcc_64
LIBS          = $(SUBLIBS) -lSDL2 -lglut -lGLU -lGL -L /home/i7469762/Documents/box2D/GLFunctionsLib/lib -lGLFunctionsLib 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		physicsworld.cpp \
		rigidbody.cpp \
		obstacles.cpp \
		GLFunctionsLib/src/GLFunctions.cpp \
		GLFunctionsLib/src/Mat4.cpp \
		GLFunctionsLib/src/Vec4.cpp \
		colours.cpp 
OBJECTS       = main.o \
		physicsworld.o \
		rigidbody.o \
		obstacles.o \
		GLFunctions.o \
		Mat4.o \
		Vec4.o \
		colours.o
DIST          = README.txt \
		box2D \
		/opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf \
		box2D.pro physicsworld.h \
		rigidbody.h \
		obstacles.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Mat4.h \
		GLFunctionsLib/include/Vec4.h \
		colours.h main.cpp \
		physicsworld.cpp \
		rigidbody.cpp \
		obstacles.cpp \
		GLFunctionsLib/src/GLFunctions.cpp \
		GLFunctionsLib/src/Mat4.cpp \
		GLFunctionsLib/src/Vec4.cpp \
		colours.cpp
QMAKE_TARGET  = Box2D
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Box2D


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: box2D.pro /opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf \
		box2D.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile box2D.pro
/opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf:
box2D.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile box2D.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		physicsworld.h \
		rigidbody.h \
		colours.h \
		easymaze.h \
		obstacles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

physicsworld.o: physicsworld.cpp physicsworld.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		rigidbody.h \
		colours.h \
		easymaze.h \
		obstacles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o physicsworld.o physicsworld.cpp

rigidbody.o: rigidbody.cpp rigidbody.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		colours.h \
		obstacles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rigidbody.o rigidbody.cpp

obstacles.o: obstacles.cpp obstacles.h \
		rigidbody.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		colours.h \
		physicsworld.h \
		easymaze.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obstacles.o obstacles.cpp

GLFunctions.o: GLFunctionsLib/src/GLFunctions.cpp GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLFunctions.o GLFunctionsLib/src/GLFunctions.cpp

Mat4.o: GLFunctionsLib/src/Mat4.cpp GLFunctionsLib/include/Mat4.h \
		GLFunctionsLib/include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mat4.o GLFunctionsLib/src/Mat4.cpp

Vec4.o: GLFunctionsLib/src/Vec4.cpp GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vec4.o GLFunctionsLib/src/Vec4.cpp

colours.o: colours.cpp colours.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colours.o colours.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

